import { writable } from 'svelte/store';

interface SelectedFeedData {
    id: string;
    title: string;
    summaryHtmlSnippet: string;
    link: string;
}

interface FeedLabel {
    [key: string]: string;
}

interface FeedVO {
    labels: FeedLabel;
    time: string; // Comes as string, parse for sorting
    // Add a unique ID property generated by getFeedItemId
    id?: string;
}

interface QueryResponse {
    summary: string;
    feeds: FeedVO[];
    count: number;
}

export const selectedFeedStore = writable<SelectedFeedData | null>(null);

export const queryFeedsStore = writable<QueryResponse | null>(null);

